version: 2

 jobs:
   build:
     ...
   deploy:
     docker:
       - image: <docker-image-name-tag>
     steps:
       - checkout
       - run:
           name: Deploy Master to Heroku
           command: |
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

 workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master # only run deploy-via-git job on master branch
